### ISSUE TITLE
Double dimensions are ignored

### ISSUE THREAD

**Issue by joren** [bseddon/XPath20#3] opened 2020-08-24 08:29 UTC
Hi Bill,

Sorry for yet another of our issues, but I'm having some trouble debugging the next issue for the Belgian taxonomy.

We have these two contexts with each time two dimensions:

```xml
    <context id="D36">
      <entity>
        <identifier scheme="http://www.fgov.be">0840732454</identifier>
      </entity>
      <period>
        <startDate>2019-01-01</startDate>
        <endDate>2019-12-31</endDate>
      </period>
      <scenario>
        <xbrldi:explicitMember dimension="d-wa:WageDimension">d-wa:LowWageMember</xbrldi:explicitMember>
        <xbrldi:explicitMember dimension="d-tu:TimeUnitDimension">d-tu:FiveDayWeekMember</xbrldi:explicitMember>
      </scenario>
    </context>
    <context id="D37">
      <entity>
        <identifier scheme="http://www.fgov.be">0840732454</identifier>
      </entity>
      <period>
        <startDate>2019-01-01</startDate>
        <endDate>2019-12-31</endDate>
      </period>
      <scenario>
        <xbrldi:explicitMember dimension="d-wa:WageDimension">d-wa:LowWageMember</xbrldi:explicitMember>
        <xbrldi:explicitMember dimension="d-tu:TimeUnitDimension">d-tu:SixDayWeekMember</xbrldi:explicitMember>
      </scenario>
    </context>
```

The `SixDayWeekMember` and `FiveDayWeekMember` each have separate tests, but on fields with the same name:

> be-tax-2020-04-30/be-tax-f-eap-5424-2020-04-30-assertion.xml
```xml
<va:valueAssertion 
	xlink:type="resource" 
	xlink:label="f-eap-5424" 
	id="f-eap-5424"
	aspectModel="dimensional"
	implicitFiltering="true"
	test="(every $item in $LabourRegulationNumberDays satisfies xs:integer($item) eq 303)"/>
```

> be-tax-f-eap-5423-2020-04-30-assertion.xml
```xml
<va:valueAssertion 
	xlink:type="resource" 
	xlink:label="f-eap-5423" 
	id="f-eap-5423"
	aspectModel="dimensional"
	implicitFiltering="true"
	test="(every $item in $LabourRegulationNumberDays satisfies xs:integer($item) eq 251)"/>
```

In this test-file we're having this data included: 
```xml
    <tax-inc:LabourRegulationNumberDaysCalendarYear-1 contextRef="D36" decimals="2" unitRef="U-EUR">251.00</tax-inc:LabourRegulationNumberDaysCalendarYear-1>
    <tax-inc:LabourRegulationNumberDaysCalendarYear-1 contextRef="D37" decimals="2" unitRef="U-EUR">303.00</tax-inc:LabourRegulationNumberDaysCalendarYear-1>
    <tax-inc:LabourRegulationNumberDaysCalendarYear-2 contextRef="D36" decimals="2" unitRef="U-EUR">251.00</tax-inc:LabourRegulationNumberDaysCalendarYear-2>
```

It now looks that the each test check all these fields, and ignore that D36 only has to be tested against the `FiveDayWeekMember` test and `D37` agains the `SixDayWeekMember` test.  
I noticed this by adding this to one of the error messages: `(= {$LabourRegulationNumberDays})` which then resulted in this output: `(= 251.00251.00251.00303.00251.00)`.

The files has a lot of other issues as well that look kind of related that it tests too much.

Her the anonymised file: 
[week.txt](https://github.com/bseddon/XPath20/files/5116637/week.txt)

It would already be a great help if you could guide me in the right direction on how I can start debugging this or in which files I have to look on why both tests were triggered.

**Comment by bseddon** [comment] 2020-08-24 09:01
I'm taking a look.  I'll post again as soon as possible.

**Comment by bseddon** [comment] 2020-08-24 11:26
My tests are set up and I can see that the assertion tests are taking into account all four 'tax-inc:LabourRegulationNumberDaysCalendarYear-1' values from the instance document when the formula indicates the explicit member filters should result in just one value being tested.  I will look into it further.

In case you want to find out what's going on, here's a sketch of what the code is doing when evaluating an assertion or other formula.

The relevant start point is the loop on line 827 in function validateVariableSets of XBRL-Formulas.php.  The beginning of this loop is a handy place to put a condition so that only relevant formulas are processed.  For example:

```php
if ( $variableSet['linkbase'] != 'be-tax-f-eap-5424-2020-04-30-assertion.xml' ) continue;
```

The purpose of each iteration of the loop is to build an in-memory representation of a formula ($variableSetInstance), create an ordered list of fact and general variables then, on line 1427, evaluate it.  This line is a good place to put a breakpoint.  The variables are ordered such that if one variable relies on the result of another they are evaluated in the correct sequence.

Line 1427 calls another function which calls VariableSet::evaluate.  This function is on line 326 of ./Resources/Variables/VariableSet.php.  Ultimately, the purpose of this function is to call Evaluation::Evaluate()(/Formulas/Evaluaton.php) which is where all the interesting stuff happens.  Until this point, it's all been validation and book-keeping.

Evaluation::processVariables() calls itself recursively to process each variable and, finally, evaluate the formula test in the context of each evaluated variable.  Putting break points on lines 289, 297, 301 will allow you to catch the point that this evaluation will take place.  

Each of these lines is a call to VariableSet::evaluateResult(),  In this function, any pre-conditions are evaluated, set of variable results constructed and the XPath expression is processed leading to a result.

Back to Evaluation::processVariables().  A really important line in this function is 129.  This calls the filter function for each variable.  The purpose of the filter function is to apply the restrictions defined in the formula, for example, applying the dimension filters.  For fact variables the filter is implemented in Factvariable::filter() on line 268 of ./Resources/Variables/FactVariable.php.  I will be spending time watching the behaviour of this function.

It's task is to create an XPath 2.0 statement that will select the subset of instance document facts that meet the filters defined for the respective FactVariable.  My guess is that something goes wrong in this filter process.  You will see that the expression to evaluation is built up in $filterExpression which is evaluated on line 487.  If you add a global variable called $debug_statements and set this variable to true before processing formulas and is you have setup a log, then the generated expression will be logged.

The results of this filter will be passed along to the next variable to be evaluated.

**Comment by bseddon** [comment] 2020-08-24 11:44
After looking at the generated filter expression the problem seems to be missing brackets.  Here is the relavant part of the expression (the tuple tests are not included and the namespaces have been replaced by ... because they don't add anything):

```xpath
xfi:fact-has-explicit-dimension-value(.,fn:QName('...','TimeUnitDimension'),fn:QName('...','SixDayWeekMember')) 
	and 
xfi:fact-has-explicit-dimension-value(.,fn:QName('...','WageDimension'),fn:QName('...','AllWageMember')) 
	or 
xfi:fact-has-explicit-dimension-value(.,fn:QName('...','WageDimension'),fn:QName('...','LowWageMember')))
```

You can see there should be brackets around the 2nd and 3rd functions.  Right now it reads:

A and B or C

but I think it should read

A and (B or C).

**Comment by bseddon** [comment] 2020-08-24 12:47
The FactVariable::filter() function calls the 'toQuery()' function of relevant ./Resources/Filters/* classes.  In this case the filter implementation causing the issue is in ExplicitDimension.php.  At the end of ExplicitDimension::toQuery() is this line:

```php
return implode( " or ", $clauses )';
```
This line needs to be modified to wrap the returned value in parentheses:
```php
return '(' . implode( " or ", $clauses ) . ')';
```
This corrects the query and, as a result, the two facts with '303' values are returned as expected.  Then when the assertion test is evaluated both fact values equal the required value and the result is 'true'.

I will now re-run the conformance tests to verify this change does not affect anything.  Assuming there is no adverse effect, I will push the change and updated the composer site.  When done, I'll let you know with another post here.

**Comment by bseddon** [comment] 2020-08-24 13:27
Thanks for the report.  The update has been committed and composer has been updated so you can update.  Hopefully this will also address the other cases you mentioned.

**Closed as completed** 2020-08-25 09:43 UTC
